### ISSUE TITLE
add self-weight case

### ISSUE THREAD

**Issue by jorgepz** [ONSAS/ONSAS.m#133]
* [x] truss elements
* [ ] tetrahedron elements
* [x] beam elements

**Comment by jorgepz** [comment]
truss self weight validated in PR #173

**Comment by jorgepz** [comment]
reabro

**Comment by jorgepz** [comment]
Faltan los tetraedros... sugiero dejarlo abierto.

**Comment by mvanzulli** [comment]
> Faltan los tetraedros... sugiero dejarlo abierto.

Okay
