### ISSUE TITLE
Simple Pendulum numerical file has been deleted. 

### ISSUE THREAD

**Issue by mvanzulli** [ONSAS/ONSAS.m#224]
Error running simplePendulum script (PendulumNL_HHT). The numerical file has been deleted. 
![image](https://user-images.githubusercontent.com/50339940/96520894-6f584a80-1246-11eb-91dd-7377594e1130.png)

simplePendulumScripts must be added or the input has to been modifyed and compare numercial solution with different tolerances.

**Comment by jorgepz** [comment]
PenduloNL_HHT file move to the test folder in commit 3c3673b10fc06fb073d8f6ca07b74fec825bd3e4
