### ISSUE TITLE
Analytic sol verif with scalar functions

### ISSUE THREAD

**Issue by mvanzulli** [ONSAS/ONSAS.m#229]
The analyticFunc should accept scalar arguments

**To Reproduce**
1. Go to 'mvanzulli/117'
2. Click on 'onsas Example beam to helical form'

**Screenshots**
![image](https://user-images.githubusercontent.com/50339940/98585865-a9959480-22a6-11eb-879d-899e2c79c1be.png)

**Additional context**
This error could be reproduce un uniformCantieleverMoment multiply and divide  the analytic function by w.

**Comment by jorgepz** [comment]
beamToHelicalForm example moved from mvanzulli/117 to master in folder other/examples-to-fix. the 117 branch is outdated https://github.com/ONSAS/ONSAS.m/pull/255 thus it is deleted.
