### ISSUE TITLE
Update angular velocity and acceleration 

### ISSUE THREAD

**Issue by mvanzulli** [ONSAS/ONSAS.m#231]
**Describe the bug**
The time step update must be separate to linear velocities and accelerations

**To Reproduce**
1. Go to 'line 196 timeStepIterationScript'. This is classical Newmark Update and should be modified

**Screenshots**
![image](https://user-images.githubusercontent.com/50339940/98701765-6693f980-2358-11eb-9585-13ae1c8b206c.png)

**Comment by jorgepz** [comment]
cierro por dejarlo en stand by
