### ISSUE TITLE
Visualización en vtk al tener elementos con diferentes secciones

### ISSUE THREAD

**Issue by JoaquinViera** [ONSAS/ONSAS.m#328]
No se puede visualizar correctamente en vtk al modelar emparrillados de vigas con diferentes secciones

**Comment by jorgepz** [comment]
gracias joaquín. tendrás alguna foto del problema? o algún ejemplo para reproducirlo?

**Comment by JoaquinViera** [comment]
Agrego un .txt con el código. no deja subir archivos de extensión  .m y no quería crear una branch para esto. Agrego imágenes de los dos casos.

Cambiando en la línea 108 (indico en negrita) el elemento 2 por el 3 ya se puede reproducir.

% Row elements
for i=1:nrows
	for j=1:(ncolumns-1)

**108**		mesh.conecCell{ ncolumns*2 + (ncolumns-1)*(i-1) + j, 1 } = [ 1 2 0 0 ncolumns*(i-1)+(j) ncolumns*(i-1)+(j+1) ] ;
	end
end

[Grid_vtk.txt](https://github.com/ONSAS/ONSAS.m/files/7529592/Grid_vtk.txt)

![Grid_2](https://user-images.githubusercontent.com/45524519/141515640-8918aa0b-e91f-4e7e-920b-4f063f8443b3.PNG)
![Grid_1](https://user-images.githubusercontent.com/45524519/141515645-3b61d902-6db3-48b8-b5c5-d0ef3f678b29.PNG)

**Comment by jorgepz** [comment]
@JoaquinViera  sugiero que subas a algún branch la corrección parcial del bug que estuvimos discutiendo el viernes... de esa forma si alguien más quiere seguirlo puede 😄

**Comment by JoaquinViera** [comment]
Esta el PR hecho en la branch Euler

**Comment by jorgepz** [comment]
el problema fue corregido en el PR #318
