### ISSUE TITLE
completar/confirmar info de autores en CITATION

### ISSUE THREAD

**Issue by JoaquinViera** [ONSAS/ONSAS.m#337]

**Comment by jorgepz** [comment]
estoy agregando el citation.cff en https://github.com/ONSAS/ONSAS.m/pull/376

tenemos que:
- [ ] conseguir orciid de @bbazzano
- [ ] conseguir orcid de  @JoaquinViera
- [ ] confirmar el orcid de @mforets   https://orcid.org/0000-0002-9831-7801
- [ ] conseguir orcid de sebastian toro
- [ ] conseguir orcied de @mvanzulli

**Comment by mvanzulli** [comment]
> estoy agregando el citation.cff en #376
> 
> tenemos que:
> 
> * [ ]  conseguir orciid de @bbazzano
> * [ ]  conseguir orcid de  @JoaquinViera
> * [ ]  confirmar el orcid de @mforets   https://orcid.org/0000-0002-9831-7801
> * [ ]  conseguir orcid de sebastian toro
> * [x]  conseguir orcid de @mvanzullihttps://orcid.org/0000-0001-6080-3815

**Comment by jorgepz** [comment]
lo dejo abierto y le cambio el nombre para esperar info pendiente...

**Comment by jorgepz** [comment]
lo doy por cerrado por ahora.

**Comment by jorgepz** [comment]
reabro para agregar orcid de sebastián toro

**Comment by jorgepz** [comment]
>     * [ ]  confirmar el orcid de @mforets   https://orcid.org/0000-0002-9831-7801

@mforets  estamos por hacer un release... podés confirmar tu orcid por favore? grazzie

**Comment by mforets** [comment]
si, es correcto

**Comment by jorgepz** [comment]
selente.

**Comment by jorgepz** [comment]
@bbazzano no tiene orcid asi que por ahora cierro el issue. A futuro se volverá a abrir si cambian los autores o bruno se hace orcid.
