### ISSUE TITLE
Check sinusoidal functions implemented in Aero Force    

### ISSUE THREAD

**Issue by mvanzulli** [ONSAS/ONSAS.m#364]
Add check in `aeroForce.m` to avoid complex results like:

```octave
 octave:47> acos(1.1)
ans =  0.00000 + 0.44357i
```

**Comment by jorgepz** [comment]
Esto ha pasado? No estará faltando dividir por una norma antes de hacer el acos?... Pregunto solo porq parece un chequeo raro de hacer si uno hace acos de algo q realmente debe ser menor o igual a 1...

**Comment by jorgepz** [comment]
agregué este comentario en el PR #365

**Comment by mvanzulli** [comment]
Closed by #365
