### ISSUE TITLE
update aerodynamic to hydrodynamic formulation

### ISSUE THREAD

**Issue by mvanzulli** [ONSAS/ONSAS.m#421]
This issue aims to fix:

- [x] Comments in `aeroForce.m`
- [x] Change fluid to a generic type of fluid including the density as an input parameter
- [x] keep only the _rigid_ aerodynamic formulation
- [x] Update `linearCantileverAero.m` example
- [x] Update `nonLinearCantileverAero.m` example
- [x] Update simple propeller example

**Comment by TheChikenfly** [comment]
I tried to change the rhoFluid from 1.2 to 1000 in AeroForce and the dynamics on the beam changes damatically: I have no high frequencies in the beam anymore wich is very convenient to reach the final state quicker!

**Comment by mvanzulli** [comment]
Great news! wait to see the CY.CD results. What do you think about adding the fluid density as a parameter into otherParams struct like:

` otherParams.fluidDensity = 1000`

And also do you find interesting to add Reynolds number as a parameter to compute drag, lift and moment coefficients?

**Comment by TheChikenfly** [comment]
`otherParams.fluidDensity = 1000` is a good idea yes!
You mean having the Reynolds number as a parameter instead of betaRel ?

**Comment by mvanzulli** [comment]
> `otherParams.fluidDensity = 1000` is a good idea yes! You mean having the Reynolds number as a parameter instead of betaRel ?
Both of them. For instance if a bluff cylinder body drag function is:
![image](https://user-images.githubusercontent.com/50339940/162118137-9d353cdd-59c2-4155-81bf-70806d4906bb.png)
we can compute inside `aeroForce.m`  the Reynolds number as $Vabs.CarateriscticDim / Kinematic viscosity$. Subsequently when `aeroForce.m` call dragFunction then the Reynolds and BetaRel are used as an input. 

I think this might be aplicable for laminar fluid flows. What do you think?
