### ISSUE TITLE
Change default dynamic parameters 

### ISSUE THREAD

**Issue by mvanzulli** [ONSAS/ONSAS.m#437]
Add default time integration methods parameters to `setDefaults.m`:

- [x] Classic trapezoidal Newmark 
- [x] Classic alpha-HHT  
- [ ] ~~Warn the user if  for these dynamic cases  `materias.density` is empty.~~
- [x] add defaults to the documentation 
- [ ] ~~Add a warning if the numerical method is not implemented~~

**Comment by jorgepz** [comment]
the newmark subtask was done in https://github.com/ONSAS/ONSAS.m/pull/445

**Comment by mvanzulli** [comment]
The HHT was solved in #451

**Comment by jorgepz** [comment]
I agree!
