### ISSUE TITLE
add water density

### ISSUE THREAD

**Issue by TheChikenfly** [ONSAS/ONSAS.m#459]
Could be nice to add a variable to decide if the structure is in Air or Water (change the fluid density in [aeroForce.m](https://github.com/ONSAS/ONSAS.m/blob/master/src/aeroForce.m) line248:  rhoFliud = 1.225 )

**Comment by mvanzulli** [comment]
Yeah it would be, I created the issue #421 for such task. If you want you could comment this there and we discuss how it woud  be more general and useful.

**Comment by jorgepz** [comment]
Indeed it is a good idea. fluidDensity could be in the ohterparams struct by the moment..

**Comment by jorgepz** [comment]
I close the issue since the discussion moved to https://github.com/ONSAS/ONSAS.m/issues/421
