### ISSUE TITLE
add working userloadfunc use example

### ISSUE THREAD

**Issue by jorgepz** [ONSAS/ONSAS.m#472]
check how is the user load func used in the static von mises problem

**Comment by TheChikenfly** [comment]
It seems the program never reads the  `userLoadsFilename` function

**Comment by jorgepz** [comment]
I still have to fix the static von mises problem to add the user load filename case

**Comment by TheChikenfly** [comment]
I don't know if it helps but it seems to work if I use 
`boundaryConds(2).loadsTimeFact = @(t) myVMLoadFunc(t)     ;
boundaryConds(2).loadsBaseVals = [ 0 0 0 0 -1 0 ] ;`
instead of `boundaryConds(2).userLoadsFilename = 'myVMLoadFunc' ;` in  static von mises

**Comment by TheChikenfly** [comment]
(buut you have to change myVMLoadFunc so that the output is a scalar)

**Comment by jorgepz** [comment]
great, thanks with that. I think this issue will be left for after the Workshop.
