### ISSUE TITLE
Clean currently not used functions

### ISSUE THREAD

**Issue by mvanzulli** [ONSAS/ONSAS.m#480]
I execute a profile with octave running `runTestProblems_local.m` and the functions that are no used are:

- [x] Actualización.m
- [x] aeroForce.m
- [ ] analyticSolVerif
- [ ] computeNormalForces
- [ ] createRectangular
- [ ] createSolidRegularMesh
- [ ] DerivFun
- [ ] linearBucklingAnalysisPlots
- [ ] loadsAngleSpring
- [ ] massMatAssembly
- [ ] MatrizMasaCompleja
- [ ] modelExtract
- [ ] stabilityAnalysis
- [ ] structsToCellsConv
- [ ] tablesFunc
- [ ] tangentInertialMassMatrix

Maybe we could define a header for each function and define a uniform nomenclature for naming functions :100:

**Comment by jorgepz** [comment]
ok. cleaning is a good idea. however runTestProblems_local might not test everything which is needed... or useful...

**Comment by mvanzulli** [comment]
I agree of course! But could revel us which functions are used and also a clue of which are not.

 >ok. cleaning is a good idea. however runTestProblems_local might not test everything which is needed... or useful... aeroForces.m is not useful?...
 emm I think is not, `hydroForce.m` is a generalization of it.

**Comment by jorgepz** [comment]
ok. go ahead with the cleaning then 🧹

**Comment by jorgepz** [comment]
i also suggest removing the comment authorship header from all the files... The license file and the acknowledgement files are clear enough...

**Comment by jorgepz** [comment]
based on this https://www.youtube.com/watch?v=BuS0mvlNo08 it is preferable to leave the copyright headers of each file... however. we should update all of them... maybe create a script to do so 🤓
