### ISSUE TITLE
Folder names "Aux" don't work in windows.

### ISSUE THREAD

**Issue by bbazzano** [ONSAS/ONSAS.m#487]
Repo can not be cloned in Windows.

It seems to be an issue with "aux" folder names in src/elements/...

**Comment by jorgepz** [comment]
Thanks a lot bruno. Important fail that was not detected by our CI.
Gracias también a Guillermo Puertas

**Comment by jorgepz** [comment]
A ver agora what happens?...

**Comment by jorgepz** [comment]
it is working in windows with github desktop. please @bbazzano try again and reopen the issue if it does not work for you.
