### ISSUE TITLE
Bug in HydroFrameForce

### ISSUE THREAD

**Issue by TheChikenfly** [ONSAS/ONSAS.m#517]
not working when initial wind velocity is 0 (for a ramp for example)

**Comment by TheChikenfly** [comment]
Pull Request [#518]

**Comment by mvanzulli** [comment]
Thxs @TheChikenfly for reporting the bug. The problem comes up when you use `hydroFrameForces.m`function and globalVIVBool. Can you explain a bit more with which combination of arguments it happens, please :petri_dish:
