### ISSUE TITLE
Document Neo-Hookean model

### ISSUE THREAD

**Issue by mvanzulli** [ONSAS/ONSAS.m#608]
Considering this strain energy function is:

 ```math
 \Psi(\mathbf{C}) = \frac{\mu}{2}(I_1 -3) + 1/D  (J -1)^2
 ```
then Cosserat is:

 ```math
 \mathbf{S} = 2 \frac{\partial \Psi }{\partial \mathbf{C}} = \mu (I_{3,3}) + \frac{2}{D}(J-1) J C^{-T}
 ```
but in ONSAS we have:

 ```matlab
S       = shear * ( eye(3) - invC ) + bulk * ( J * (J-1)* invC) ;
```

Useful identities:

 ```math
J  = \sqrt(det(\mathbf{C}))
```
 ```math
\frac{\partial J}{\partial \mathbf{C}}  = \frac{J \mathbf{C}^{-T}}{2}  
```
 ```math
\frac{\partial I_1}{\partial \mathbf{C}}  = I_{3,3}  
```

**Comment by bbazzano** [comment]
I checked this and I think that to have the $S$ tensor given in the [uniaxial compression example](https://onsas.github.io/ONSAS.m/dev/examples/uniaxialCompression/), one should have the following strain energy expression:
$$\Psi = \mu (I_1 - \ln(J))+\frac{K}{2}(J-1)^2$$

The derivative $\frac{\partial \Psi}{\partial C}$ would be as follows:

$$ \frac{\partial \Psi}{\partial C} = \mu(\text{Id} -\frac{1}{J}JC^{-1}) + \frac{K}{2}2(J-1)JC^{-1} $$

$$ \frac{\partial \Psi}{\partial C} = \mu(\text{Id} - C^{-1}) + KJ(J-1)C^{-1} $$

@mvanzulli let me know what you think.

**Comment by jorgepz** [comment]
awesome! thanks Bruno. that's the one

**Comment by bbazzano** [comment]
One comment, in my reply I was assuming that $J=\det(C)$, while the documentation includes a square root.
Please check this for consistency.

**Comment by mvanzulli** [comment]
> I checked this and I think that to have the S tensor given in the [uniaxial compression example](https://onsas.github.io/ONSAS.m/dev/examples/uniaxialCompression/), one should have the following strain energy expression: Ψ=μ(I1−ln⁡(J))+K2(J−1)2
> 
> The derivative ∂Ψ∂C would be as follows:
> 
> ∂Ψ∂C=μ(Id−1JJC−1)+K22(J−1)JC−1
> 
> ∂Ψ∂C=μ(Id−C−1)+KJ(J−1)C−1
> 
> @mvanzulli let me know what you think.

This $ln(J)$ leads to: 
```math
\frac{\partial ln(J)}{ \partial \mathcal{C}} = \frac{1}{J} \frac{\partial J}{\partial \mathcal{C}}= \frac{1}{J} \frac{\sqrt{(det(\mathcal{C})}}{\partial \mathcal{C} } = \frac{1}{J}\frac{1}{2\sqrt{det(\mathcal{C}})}det(\mathcal{C})\mathcal{C}^{-T} = \frac{1}{J}\frac{1}{2J}J^2\mathcal{C}^{-T} = \frac{\mathcal{C}^{-T}}{2}
```

Agree that in Cosserat we have we have this additional term: $C^{-1}$

**Comment by jorgepz** [comment]
Great interaction. I think the function is 

```math
\Psi = \frac{\mu}{2} (I_1 - 2 \ln(J))+\frac{K}{2}(J-1)^2
```

Eq 3.34 from [Gurtin](https://www.amazon.com/Introduction-Continuum-Mechanics-Mathematics-Engineering/dp/0123097509/ref=sr_1_2?qid=1675883025&refinements=p_27%3AMorton+E.+Gurtin&s=books&sr=1-2) gives:
```math
\frac{\partial det( \mathbf{A} )}{\partial \mathbf{A} } = (det(\mathbf{A})) \mathbf{A}^{-T}
```
for any tensor $\mathbf{A}$

That confirms equation 6.31 from [Holzapfel](https://www.wiley.com/en-us/Nonlinear+Solid+Mechanics%3A+A+Continuum+Approach+for+Engineering-p-9780471823193)

```math
\frac{\partial I_3 }{\partial \mathbf{C} } = I_3 \mathbf{C}^{-1}
```
where $I_3$ is the third invariant of $\mathbf{C}$.

Using the chain rule and that $J$ is the third invariant of $\mathbf{F}$ we get eq. 6.82 from Holzapfel:
```math
\frac{\partial J }{\partial \mathbf{C} } = \frac{J}{2} \mathbf{C}^{-1}
```

Then the second piola tensor is

```math
\mathbf{S} = 2\frac{\partial \Psi}{\partial C} = 2 \frac{\mu}{2} (\mathbf{I} - 2\frac{1}{J}\frac{1}{2}JC^{-1}) + 2\frac{K}{2}2(J-1)\frac{1}{2}JC^{-1}
```
which leads to

```math
\mathbf{S} = \mu (\mathbf{I} - \mathbf{C}^{-1} ) + K (J-1) J \mathbf{C}^{-1}
```

**Comment by bbazzano** [comment]
@mvanzulli thanks for spotting this! I agree with the calculation you showed in your previous comment.

It's too bad that I used a definition for $J$ which did not match the one in the documentation.

To summarize, keeping with the convention that $J=\sqrt{\det(C)}$, the strain energy $\Psi$ and the $S$ tensor are as follow:

$$\Psi = \mu (I_1 - 2\ln(J))+K(J-1)^2$$

$$\frac{\partial \Psi}{\partial C} = \mu(\text{Id} - C^{-1}) + KJ(J-1)C^{-1}$$

I believe this strain energy should be the one shown in the documentation and code comments.

**Comment by jorgepz** [comment]
Thanks @bbazzano . To what you did I would add an $1/2$, since

```math
S = 2 \frac{\partial \Psi}{\partial \mathbf{C}}
``` 

we can also discuss this on gitter...

**Comment by mvanzulli** [comment]
I have opened this [PR](https://github.com/ONSAS/ONSAS.m/pull/605). I have included @jorgepz's expression which I think is the correct one:

```math
\Psi = \frac{\mu}{2} (I_1 - 2 \ln(J))+\frac{K}{2}(J-1)^2
```

We can discuss this on firday and then set #605 ready for review.

**Comment by jorgepz** [comment]
I think we can review the PR and in case we need to re-discuss this reopen the issue.
