### ISSUE TITLE
Include a more complete drag formulation for circular cross-sections

### ISSUE THREAD

**Issue by frederickgosselin** [ONSAS/ONSAS.m#617]
Hi Jorge and Mauricio,
About the normal drag force per unit length on the cylinder, from my understanding, the current implementation uses a formulation
```math
F_d=\frac{1}{2}\rho C_D U^2 d
```
 with a constant C_D. This is appropriate for a Reynolds number in the range 100-10^5.
 For Alexandre's problem, to provide damping at low velocity or even in zero-flow conditions, it'd be nice to have a drag coefficient that varies with the Reynolds number R_e in this way
```math
C_D=11*R_e^{−0.75}+0.9*(1−\exp(−1000/R_e))+1.2*(1−\exp(−(R_e/4500)^{0.7})),
```
where the Reynolds number is defined as R_e=d*|U_rel|/nu, with U_rel being the instantaneous relative velocity between the cylinder element and the flow.
The advantage of this formulation is that at low R_e, it enforces a drag force that is linear with the relative velocity, hence creating damping.
There should be a warning in the code if R_e exceeds 2*10^5 in which case the drag coefficient relation breaks down as it does not account for the drag crisis.

Reference for the drag formulation.
https://ascelibrary.org/doi/10.1061/%28ASCE%29HY.1943-7900.0000722

**Comment by jorgepz** [comment]
Hi Frederick, thank you very much for your comment! I am tagging this as an improvement to do in the near future. If any question emerges we follow the discussion in this thread.

**Comment by mvanzulli** [comment]
Excellent, maybe [linear aerodynamics example](https://onsas.github.io/ONSAS.m/dev/examples/linearAerodynamics/) can be the one to validate this feature.

**Comment by mvanzulli** [comment]
I think we can consider two ways on how the user can define aero/hydro - dynamic cross section parameters
```matlab
elements(2).aeroCrossSecParams = 'circle'
elements(2).aeroNumericalAeroParms = [numGaussPoints computeAeroTangMatrix] % optional
```
For a `generic` cross section:
```matlab
elements(2).aeroCrossSecParams = 'generic'
elements(2).aeroCrossSecParams = [chord_x, chord_y, chord_z, "drag_f_name", "lift_f_name","pitch_f_name"]
elements(2).aeroNumericalAeroParms = [numGaussPoints computeAeroTangMatrix] % optional
```

Another option would be to include this into `crossSectionProps` function.

**Comment by jorgepz** [comment]
I think we have a good opportunity to optimize some of the VIV input parameters and have a simpler interface. For instance I would not set the field `circle` since it should be defined in the `element` struct... we can discuss this in the next onsas meeting or in these days.

**Comment by mvanzulli** [comment]
According to the discussion with @jorgepz and @TheChikenfly  we define that:

- The aerodynamic parameters of the element should be separated fields into the `Elements` struct. 
```matlab
elements(2).chrodVector = [cx,cy,cz]
elements(2).dragCoefFunction = "my_drag"
elements(2).liftCoefFunction = "my_lift"
elements(2).pitchCoefFunction = "my_pitch"
elements(2).numGaussPoints = 4
elements(2).computeStiffAeroMatrix = true
```
If a `circle` or `pipe` cross-section is defined then `setDefaults.m` will set defaults values for these fields including the drag force aforementioned.
