### ISSUE TITLE
Odd octave tests output 

### ISSUE THREAD

**Issue by mvanzulli** [ONSAS/ONSAS.m#637]
In #636 my local version is failing but remote tests in CI is passing. 

![image](https://user-images.githubusercontent.com/50339940/221437745-67f90e0e-ae35-4ef8-9729-2e5638543c08.png)

Is this wrong ?

**Comment by jorgepz** [comment]
indeed... the problem is that that workflow is downloading the master version! well found!

**Comment by jorgepz** [comment]
now octave_tests should fail in https://github.com/ONSAS/ONSAS.m/pull/636 ...
