### ISSUE TITLE
Add current solution information as input in the userloadfunction for Newmark Method

### ISSUE THREAD

**Issue by santiago-correa-89** [ONSAS/ONSAS.m#662]
update the newmark method to add the current solution information as input to the userloadfunction

**Comment by jorgepz** [comment]
Thanks Santiago. I am closing this issue since (I think) the user load function is called in the same way for all the resolution methods... i suggest discussing this on today's meeting at 3 pm or via the slack channel.

**Comment by jorgepz** [comment]
as discussed in the onsas-meeting, there is indeed a change to do in the call of the newmark method to pass arguments. thanks @santiago-correa-89 !
